// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// SkillsHandler is an autogenerated mock type for the SkillsHandler type
type SkillsHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *SkillsHandler) Create(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *SkillsHandler) Delete(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// Find provides a mock function with given fields: _a0, _a1
func (_m *SkillsHandler) Find(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// FindAll provides a mock function with given fields: _a0, _a1
func (_m *SkillsHandler) FindAll(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}
